sudo: required
services:
  - docker

before_install:
  - docker build -t alectric/react-test:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alectric/react-test npm test

after_success:
  - docker build -t alectric/multi-client ./client
  - docker build -t alectric/multi-nginx ./nginx
  - docker build -t alectric/multi-server ./server
  - docker build -t alectric/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push to docker hub
  - docker push alectric/multi-client
  - docker push alectric/multi-nginx
  - docker push alectric/multi-server
  - docker push alectric/multi-worker
